### ISSUE TITLE
Configurable Keywords

### ISSUE THREAD

**Issue by DasBen** [gkampitakis/github-action-todo-commenter#13]
Hey! First thank you for this great Action! 

I'm not the best in JS/Typescript so let me tell you that it would be wonderful if the Keywords TODO/FIXME could be configurable. I would really like to automatically search for DOCME too and hardcoding it is one way, but making it configurable would be more future proof.

Is anything like this in the works, or could be done by anyone working on this project?

**Comment by gkampitakis** [comment]
Hi 👋 . Thanks for opening this issue. 

This should already be supported, but not documented 😓 https://github.com/gkampitakis/github-action-todo-commenter/blob/2f1c032cecb466ca4676ad3e1042b5fd98625707/action.yaml#L20

and 

https://github.com/gkampitakis/github-action-todo-commenter/blob/2f1c032cecb466ca4676ad3e1042b5fd98625707/src/action-parameters.ts#L7

```yaml
name: Todo Comments
on: [pull_request]

jobs:
  todo-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Todo Comments
        uses: gkampitakis/github-action-todo-commenter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-pattern: '.js$|.snap$'
          review-message: "Please take a look :eyes:"
          # this is what you could add
          tags:  "TODO:,FIXME:,BUG:,DOCME:"
```

could you give this a try and see if it works for you? If this addresses your issue i ll create a pull request documenting this.
